default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=2048']
      - id: check-ast
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: detect-aws-credentials
      - id: name-tests-test
      - id: mixed-line-ending
        args: ['--fix=auto']
      - id: no-commit-to-branch
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.13
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - annotated-types==0.6.0
          - types-MarkupSafe==1.1.10
          - types-pytz==2023.3.1.1
          - types-ujson==5.9.0.0
          - types-urllib3==1.26.25.14
          - pyarrow-stubs==10.0.1.7
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: python
        pass_filenames: false
        always_run: true
